### ISSUE TITLE
cannot download dataset

### ISSUE THREAD

**Issue by wpfhtl** [castacks/mvs_gi#16]
It shows: This site can’t be reached.
wget https://airlab-share.andrew.cmu.edu:8081/MVS_Fisheye_Dataset/tar_list_train.txt
wget https://airlab-share.andrew.cmu.edu:8081/MVS_Fisheye_Dataset/download_train.sh

**Comment by HalleyJiang** [comment]
Me too. Waiting for the dataset.

**Comment by huyaoyu** [comment]
> It shows: This site can’t be reached. wget https://airlab-share.andrew.cmu.edu:8081/MVS_Fisheye_Dataset/tar_list_train.txt wget https://airlab-share.andrew.cmu.edu:8081/MVS_Fisheye_Dataset/download_train.sh



> Me too. Waiting for the dataset.

Please refer to the latest README.md for the instructions of downloading the dataset, models, and etc. 

Feel free to open new issues if there are problems downloading.

Thank you!
